baseURL = 'https://groupdocs-policies-test.netlify.app/'
languageCode = 'en-us'
title = 'Policies - Groupdocs'
theme = "policies"
enableRobotsTXT = true

[module]
[[module.mounts]]
 source = "assets/images"
 target = "assets/images"